# Generated by Django 2.0.4 on 2018-05-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUsr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logfld', models.CharField(max_length=40)),
                ('passfld', models.CharField(max_length=40)),
                ('langfld', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Creating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputfld', models.IntegerField()),
                ('choicebox', models.CharField(choices=[('n', 'Notes'), ('e', 'Events'), ('t', 'Todos'), ('u', 'Users')], max_length=4)),
            ],
        ),
    ]
