# Generated by Django 2.0.2 on 2018-02-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='added_date',
            field=models.DateField(default='2018-01-01'),
        ),
        migrations.AddField(
            model_name='event',
            name='added_time',
            field=models.TimeField(default='00:00:00:000000'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='2018-01-01'),
        ),
    ]
