# Generated by Django 2.0.2 on 2018-02-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_auto_20180218_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default='opened', max_length=64),
        ),
    ]
