# Generated by Django 2.0.2 on 2018-02-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='added_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='added_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
