# Generated by Django 2.0.1 on 2018-02-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_auto_20180225_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='added_date',
            field=models.DateField(default='2018-01-01'),
        ),
        migrations.AlterField(
            model_name='event',
            name='added_time',
            field=models.TimeField(default='00:00:00:000000'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='2018-01-01'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(),
        ),
    ]
