# Generated by Django 2.0.1 on 2018-03-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0005_auto_20180225_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notified_already',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='should_notify_days',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='should_notify_hours',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='should_notify_minutes',
            field=models.SmallIntegerField(default=0),
        ),
    ]
