# Generated by Django 2.0.2 on 2018-04-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0006_auto_20180302_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
