# Generated by Django 2.0.2 on 2018-04-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0007_event_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
