# Generated by Django 2.0.5 on 2018-05-27 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0010_auto_20180525_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete={1}, to=settings.AUTH_USER_MODEL),
        ),
    ]
