

# -- Главная после авторизации--
title = 'Главная'
notes_title = 'Заметки'
calendars_title = 'Календарь'
reminders_title = 'Напоминания'
account_title = 'Личный кабинет'
quit_title = 'Выйти'
navigation_title = 'Навигация'
resources_title = 'Ресурсы'
social_network_title = 'Соц. сети'
help_title = 'Справка'


nearest_event_title = 'Ближайшее мероприятие'
closest_reminder_title = 'Скорейшее напоминание'
latest_note_title = 'Последняя заметка'
no_events_title = 'Нет событий'
no_notes_title = 'Нет заметок'
no_todo_title = 'Нет напоминаний'


# --Заметки--

latest_notes = 'Последние заметки'
notes_showall = 'Показать все'

notes_create = 'Создание заметки'
notes_name = 'Название'
notes_total = 'Всего заметок'
notes_text = 'Текст'
notes_audio = 'Записать аудио'
notes_cancel = 'Отменить'
notes_add = 'Создать'
notes_delete = 'Удалить'
notes_listen = 'Прослушать'
notes_edit = 'Редактировать'
notes_save = 'ОК'
notes_edit_title = 'Редактировать заметку'
notes_changename = 'Изменить название'
notes_changetext = 'Изменить текст'
notes_rewrite_audio = 'Переписать аудио'
notes_text_count = 'текстовых'
notes_voice_count = 'голосовых'
notes_edit_title1 = 'Редактирование заметки'
notes_save1 = 'Сохранить'


# --Календарь--

closest_events_calendar = 'Ближайшие события календаря'
events_onday = 'На день'
events_onweek = 'На неделю'
events_total = 'Всего событий'
events_today = 'Событий за сегодня'
events_yesterday = 'Событий за вчера'
events_week = 'Событий за неделю'
events_month = 'Событий за месяц'
events_year = 'Событий за год'

calendar_nothing_planned = 'Ничего не запланировано'
calendar_create = 'Создание мероприятия'
calendar_name = 'Название'
calendar_choosedate = 'Выбрать дату'
calendar_choosetime = 'Выбрать время'
calendar_chooseplace = 'Выбрать место'
calendar_chooseplace1 = 'Выбор места'
calendar_description = 'Описание'
calendar_private_event = 'Приватное мероприятие'
calendar_cancel = 'Отменить'
calendar_add = 'Создать'
calendar_onthemap = 'Посмотреть на карте'
calendar_push = 'Отправить'
calendar_check_comments = 'Посмотреть комментарии'
calendar_close = 'Закрыть'
calendar_delete = 'Удалить'
calendar_save = 'ОК'
calendar_place_and_time = 'Место и время по желанию'
calendar_all_day = 'Весь день'
calendar_editing_an_event = 'Редактирование мероприятия'
calendar_changename = 'Изменить название'
calendar_change_description = 'Изменить описание'
calendar_audio = 'Записать аудио'
calendar_savechanges = 'Сохранить'
calendar_today_event = 'События на сегодня'
calendar_map_events = 'События на карте'
calendar_my_events = 'Мои события'
calendar_first_new = 'Сначала новые'
calendar_first_old = 'Сначала старые'
calendar_A_Z = 'A..Я'
calendar_Z_A = 'Я..А'
calendar_map = 'Карта'
calendar_synchronisation = 'Синхронизация'
calendar_save_all_events_to_file = 'Сохранить все события в файл'
calendar_all_events = 'все события'
calendar_save_part_of_events_to_file = 'Сохранить часть событий в файл'
calendar_download_all_events_from_file = 'Загрузить все события из файла'
calendar_download_part_of_events_to_file = 'Загрузить часть событий из файла'
calendar_chose_event_to_save = 'Выберите события для сохранения'
calendar_recommended_events = 'Рекомндованные события'


# --Напоминания--

latest_reminders = 'Последние напоминания'
closed_reminders = 'Завершенные напоминания'
reminders_showall = 'Показать все'
total_reminders = 'Всего напоминаний'
active_reminders = 'Активных напоминаний'
closed_reminders_count = 'Завершенных напоминаний'

reminders_create = 'Создание напоминания'
reminders_name = 'Название'
reminders_text = 'Текст'
reminders_priority = 'Приоритет'
reminders_audio = 'Записать аудио'
reminders_cancel = 'Отменить'
reminders_add = 'Создать'
reminders_accomplish_to = 'Выполнить к'
reminders_status = 'Статус'
reminders_edit = 'Редактировать'
reminders_save = 'ОК'
reminders_changename = 'Изменить имя'
reminders_changetext = 'Изменить тексть'
reminders_changedeadline = 'Изменить дедлайн'
reminders_changepriority = 'Изменить приоритет'
reminders_savechanges = 'Сохранить'
reminders_synchronisation = 'Синхронизация'
reminders_savealltofile = 'Сохранить все напоминания в файл' 
reminders_saveparttofile = 'Сохранить часть напоминаний в файл'
reminders_upload_allfromfile = 'Загрузить все напоминания из файла'
reminders_upload_partfromfile = 'Загрузить некоторые напоминания из файла'
reminders_synchronize = 'Синхронизировать'
reminders_delete = 'Удалить'
reminders_changename1 = 'Изменить название'
reminders_chose_reminds_for_save = 'Выберите напоминания для сохранения'
reminders_accomplish_task = 'Выполнение задачи'
reminders_back = 'Назад'
reminders_not_executed = 'Не выполнено'


# --Личный кабинет --

profile_nickname = 'Ник'
profile_name = 'Имя'
profile_surname = 'Фамилия'
profile_email = 'Эл.почта'
profile_edit = 'Редактировать профиль'
profile_oldpass = 'Старый пароль'
profile_newpass = 'Новый пароль'
profile_newpassagain = 'Новый пароль еще раз'
profile_change_avatar = 'Изменить аватар'
profile_cancel = 'Отменить'
profile_save = 'Сохранить'
profile_change_password = 'Изменить пароль'
profile_settings = 'Настройки'
profile_tembrvoice = 'Выберите тембр голоса Морриса: '
profile_lowvoice = 'Низкий'
profile_mediumvoice = 'Средний'
profile_highvoice = 'Высокий'
profile_language = 'Выберите язык:'
profile_russian = 'Русский'
profile_english = 'Английский'
profile_germany = 'Немецкий'


# --Остальное --

good_night = "Доброй ночи"
good_morning = "Доброе утро"
good_day = "Добрый день"
good_evening = "Добрый вечер"
