

# -- Главная после авторизации--
title = 'Главная'
notes_title = 'Заметки'
calendars_title = 'Календарь'
reminders_title = 'Напоминания'
account_title = 'Личный кабинет'
quit_title = 'Выйти'
navigation_title = 'Навигация'
resources_title = 'Ресурсы'
social_network_title = 'Соц. сети'
help_title = 'Справка'


nearest_event_title = 'Ближайшее мероприятие'
closest_reminder_title = 'Скорейшее напоминание'
latest_note_title = 'Последняя заметка'


# --Заметки--

latest_notes = 'Последние заметки'
notes_showall = 'Показать все'

notes_create = 'Создание заметки'
notes_name = 'Название'
notes_text = 'Текст'
notes_audio = 'Записать аудио'
notes_cancel = 'Отменить'
notes_add = 'Создать'
notes_delete = 'Удалить'
notes_listen = 'Прослушать'
notes_edit = 'Редактировать'
notes_save = 'ОК'
notes_edit_title = 'Редактировать заметку'
notes_changename = 'Изменить название'
notes_changetext = 'Изменить текст'
notes_rewrite_audio = 'Переписать аудио'


# --Календарь--

closest_events_calendar = 'Ближайшие события календаря'
events_onday = 'На день'
events_onweek = 'На неделю'
events_total = 'Всего событий'
events_today = 'Событий за сегодня'
events_yesterday = 'Событий за вчера'
events_week = 'Событий за неделю'
events_month = 'Событий за месяц'
events_year = 'Событий за год'

calendar_create = 'Создание мероприятия'
calendar_name = 'Название'
calendar_choosedate = 'Выбрать дату'
calendar_choosetime = 'Выбрать время'
calendar_chooseplace = 'Выбрать место'
calendar_description = 'Описание'
calendar_private_event = 'Приватное мероприятие'
calendar_cancel = 'Отменить'
calendar_add = 'Создать'
calendar_onthemap = 'Посмотреть на карте'
calendar_push = 'Отправить'
calendar_check_comments = 'Посмотреть комментарии'
calendar_close = 'Закрыть'
calendar_delete = 'Удалить'
calendar_save = 'ОК'


# --Напоминания--

latest_reminders = 'Последние напоминания'
closed_reminders = 'Завершенные напоминания'
reminders_showall = 'Всего напоминаний'
total_reminders = 'Всего напоминаний'
active_reminders = 'Активных напоминаний'

reminders_create = 'Создание напоминания'
reminders_name = 'Название'
reminders_text = 'Текст'
reminders_priority = 'Приоритет'
reminders_audio = 'Записать аудио'
reminders_cancel = 'Отменить'
reminders_add = 'Создать'
reminders_accomplish_to = 'Выполнить к'
reminders_status = 'Статус'
reminders_edit = 'Редактировать'
reminders_save = 'ОК'
reminders_changename = 'Изменить имя'
reminders_changetext = 'Изменить тексть'
reminders_changedeadline = 'Изменить дедлайн'
reminders_changepriority = 'Изменить приоритет'
reminders_savechanges = 'Сохранить'
reminders_synchronisation = 'Синхронизация'
reminders_savealltofile = 'Сохранить все напоминания в файл' 
reminders_saveparttofile = 'Сохранить часть напоминаний в файл'
reminders_upload_allfromfile = 'Загрузить все напоминания из файла'
reminders_upload_partfromfile = 'Загрузить некоторые напоминания из файла'
reminders_synchronize = 'Синхронизировать'


# --Личный кабинет --

profile_nickname = 'Ник'
profile_name = 'Имя'
profile_surname = 'Фамилия'
profile_email = 'Эл.почта'
profile_edit = 'Редактировать профиль'
profile_oldpass = 'Старый пароль'
profile_newpass = 'Новый пароль'
profile_newpassagain = 'Новый пароль еще раз'
profile_change_avatar = 'Изменить аватар'
profile_cancel = 'Отменить'
profile_save = 'Сохранить'
profile_change_password = 'Изменить пароль'
profile_settings = 'Настройки'
profile_tembrvoice = 'Выберите тембр голоса Морриса: '
profile_lowvoice = 'Низкий'
profile_mediumvoice = 'Средний'
profile_highvoice = 'Высокий'
profile_language = 'Выберите язык:'
profile_russian = 'Русский'
profile_english = 'Английский'
profile_germany = 'Немецкий'
