# Generated by Django 2.0.2 on 2018-04-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='deadline',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='todos',
            name='priority',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='todos',
            name='text',
            field=models.CharField(default='time', max_length=600),
        ),
    ]
