# Generated by Django 2.0.2 on 2018-04-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180412_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='deadline',
            field=models.DateTimeField(default=None),
        ),
    ]
