# Generated by Django 2.0.5 on 2018-05-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20180414_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='text',
        ),
        migrations.AlterField(
            model_name='todos',
            name='deadline',
            field=models.DateTimeField(default='2018-06-01 00:00'),
        ),
    ]
