# Generated by Django 2.0.2 on 2018-05-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20180414_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='smart_priority',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='todos',
            name='text',
            field=models.CharField(default='text', max_length=600),
        ),
    ]
