# Generated by Django 2.0.2 on 2018-02-18 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.TimeField(default='2018-01-01', max_length=20)),
                ('added_date', models.DateField(default='00-00', max_length=20)),
                ('priority', models.CharField(default='priority', max_length=100)),
                ('status', models.CharField(default='in progress', max_length=128)),
                ('deadline', models.CharField(default='deadline', max_length=128)),
                ('text', models.CharField(default='time', max_length=200)),
                ('title', models.CharField(default='title', max_length=128)),
                ('user', models.ForeignKey(default=1, on_delete={1}, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
