# Generated by Django 2.0.2 on 2018-03-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='added_date',
        ),

        migrations.AlterField(
            model_name='todos',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
