# Generated by Django 2.0.2 on 2018-03-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='todos',
            name='added_time',
        ),
        migrations.AddField(
            model_name='todos',
            name='added_date_and_time',
            field=models.DateTimeField(auto_now_add=True)
        ),
    ]
