# Generated by Django 2.0.2 on 2018-02-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
        migrations.AlterField(
            model_name='notes',
            name='added_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
