# Generated by Django 2.0.2 on 2018-03-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='last_edit_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
