# Generated by Django 2.0.2 on 2018-04-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20180318_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='name',
            field=models.CharField(default='title', max_length=128),
        ),
    ]
