# Generated by Django 2.0.2 on 2018-02-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='data',
            field=models.TextField(),
        ),
    ]
