# Generated by Django 2.0.5 on 2018-05-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20180407_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='name',
            new_name='title',
        ),
    ]
