# Generated by Django 2.0.2 on 2018-02-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20180218_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
