# Generated by Django 2.0.5 on 2018-05-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20180524_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='data_part',
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(default='title', max_length=45),
        ),
    ]
