# Generated by Django 2.0.5 on 2018-05-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20180524_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='is_voice',
        ),
    ]
