# Generated by Django 2.0.2 on 2018-02-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20180218_1014'),
        ('notes', '0004_auto_20180218_1012'),
    ]

    operations = [
    ]
