# Generated by Django 2.0.5 on 2018-05-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_remove_notes_is_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(default='title', max_length=40),
        ),
    ]
