# Generated by Django 2.0.2 on 2018-03-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_notes_is_voise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='is_voise',
            new_name='is_voice',
        ),
    ]
