# Generated by Django 2.0.2 on 2018-03-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20180304_0709'),
        ('notes', '0004_auto_20180218_1012'),
    ]

    operations = [
    ]
