# Generated by Django 2.0.2 on 2018-03-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_merge_20180304_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='last_edit_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='notes',
            name='data',
            field=models.TextField(),
        ),
    ]
