# Generated by Django 2.0.5 on 2018-05-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20180525_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesfolder',
            name='recently_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
