# Generated by Django 2.0.2 on 2018-03-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20180316_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='data_part',
            field=models.TextField(default='...'),
        ),
    ]
