# Generated by Django 2.0.5 on 2018-05-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_notesfolder_recently_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
