# Generated by Django 2.0.2 on 2018-03-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_notes_data_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='data_part',
            field=models.TextField(default='...', max_length=128),
        ),
        migrations.AlterField(
            model_name='notes',
            name='name',
            field=models.CharField(default='title', max_length=19),
        ),
    ]
