# Generated by Django 2.0.5 on 2018-05-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_notes_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
