# Generated by Django 2.0.5 on 2018-05-27 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_auto_20180527_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='last_edit_time',
        ),
    ]
