# Generated by Django 2.0.5 on 2018-05-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_remove_notes_last_edit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='added_time',
            field=models.DateTimeField(),
        ),
    ]
