# Generated by Django 2.0.2 on 2018-03-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmmailkey',
            name='email',
            field=models.CharField(max_length=150),
        ),
    ]
