# Generated by Django 2.0.1 on 2018-02-24 21:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUpKeys',
            new_name='SignUpKey',
        ),
    ]
