# Generated by Django 2.0.1 on 2018-02-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180225_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupkey',
            name='expiration_date',
            field=models.DateField(default='2018-01-01'),
        ),
    ]
