# Generated by Django 2.0.1 on 2018-02-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180225_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupkey',
            name='expiration_date',
            field=models.DateField(default='2018-01-01'),
        ),
    ]
