# Generated by Django 2.0.5 on 2018-05-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='timezone',
            field=models.CharField(default='Europe/Moscow', max_length=50),
        ),
    ]
